syntax = "proto3";

option csharp_namespace = "SmartHotel.GrpcProtos";

package GrpcProtos ;

import "google/protobuf/empty.proto" ;
import "common.proto";
import "google/protobuf/timestamp.proto";
//import "Room.proto";
import "google/protobuf/struct.proto";

service Agreement{
	rpc CreateAgreement (CreateAgreementRequest) returns (AgreementDTO) ;
	rpc GetAllAgreement (google.protobuf.Empty) returns (Agreements);
	rpc UpdateAgreement (AgreementDTO) returns (google.protobuf.Empty);
	rpc AddAgreement(AgreementDTO) returns (google.protobuf.Empty);
	rpc	RemoveAgreement (AgreementDTO) returns (google.protobuf.Empty);
	rpc DeleteAgreement (DeleteRequestDTO) returns (google.protobuf.Empty);
}
message AgreementDTO{
	string clientName = 1;
	string ClientEmail =2;
	google.protobuf.Timestamp startDate = 3;
	google.protobuf.Timestamp finalDate = 4;
	RoomDTO room = 5;
	Price price = 6;
	string roomId = 7;
	string id = 8;
}
message Agreements{
	repeated AgreementDTO item = 1;
}
message NullableAgreementDTO {
	oneof kind{
	AgreementDTO room = 1;	
	google.protobuf.NullValue null = 2;	
	}
}
message CreateAgreementRequest {
	string clientName = 1;
	string ClientEmail = 2;
	google.protobuf.Timestamp startDate = 3;
	google.protobuf.Timestamp finalDate = 4;
	RoomDTO room = 5;
	Price price = 6;
	string roomId = 7;
	string id = 8;
}