﻿syntax = "proto3";

option csharp_namespace = "SmartHotel.GrpcProtos";

package GrpcProtos;

import "google/protobuf/empty.proto";
import "Common.proto";

service Smoke{
	rpc CreateSmoke (CreateSmokeRequest) returns (SmokeDTO);
	rpc GetSmoke (GetRequest) returns (NullableSmokeDTO);
	rpc GetAllSmoke (google.protobuf.Empty) returns (Smokes);
	rpc UpdateSmoke (SmokeDTO) returns (google.protobuf.Empty);
	rpc DeleteSmoke (DeleteRequestDTO) returns (google.protobuf.Empty);
}

message SmokeDTO{
	string id = 1;
	double value = 2;
	double reference = 3;
	Room room = 4;
}

message Smokes{ 
	   repeated SmokeDTO
items = 1;
}

message NullableSmokeDTO{
	oneof kind{
		LightDTO Smoke = 1;
	}
}

message CreateSmokeRequest{ 
	double value = 1;
	double reference = 2;
	Room room = 3;
}