﻿syntax = "proto3";

option csharp_namespace = "SmartHotel.GrpcProtos";

package GrpcProtos;

import "google/protobuf/empty.proto";
import "Common.proto";

service Light{
	rpc CreateLight (LightCreationDTO) returns (google.protobuf.Empty);
	rpc GetAllLight (GetRequestDTO) returns (LightDTO);
	rpc UpdateLight (LightDTO) returns (google.protobuf.Empty);
	rpc AddVariableToLight (VariableLightRelationDTO) returns (google.protobuf.Empty);
	rpc RemoveVariableFromLight (VariableLightRelationDTO) returns (google.protobuf.Empty);
	rpc DeleteLight (DeleteRequestDTO) returns (google.protobuf.Empty);
}