syntax = "proto3";

option csharp_namespace = "SmartHotel.GrpcProtos";

package GrpcProtos ;

import "google/protobuf/empty.proto" ;
import "common.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/struct.proto";

service Agreement{
	rpc CreateAgreement (CreateAgreementRequest) returns (AgreementDTO) ;
	rpc GetAllAgreement (google.protobuf.Empty) returns (Agreements);
	rpc UpdateAgreement (AgreementDTO) returns (google.protobuf.Empty);
	rpc AddAgreement(AgreementDTO) returns (google.protobuf.Empty);
	rpc	RemoveAgreement (AgreementDTO) returns (google.protobuf.Empty);
	rpc DeleteAgreement (DeleteRequestDTO) returns (google.protobuf.Empty);
}
message AgreementDTO{
	string clientName = 1;
	string ClientEmail =2;
	google.protobuf.Timestamp startDate = 3;
	google.protobuf.Timestamp finalDate = 4;
	RoomDTO room = 5;
	Price price = 6;
	string roomId = 7;
	string id = 8;
}
message Agreements{
	repeated AgreementDTO item = 1;
}
message NullableAgreementDTO {
	oneof kind{
	AgreementDTO room = 1;	
	google.protobuf.NullValue null = 2;	
	}
}
message CreateAgreementRequest {
	string clientName = 1;
	string ClientEmail = 2;
	google.protobuf.Timestamp startDate = 3;
	google.protobuf.Timestamp finalDate = 4;
	RoomDTO room = 5;
	Price price = 6;
	string roomId = 7;
	string id = 8;
}
service Light{
	rpc CreateLight (CreateLightRequest) returns (LightDTO);
	rpc GetLight (GetRequestDTO) returns (NullableLightDTO);
	rpc GetAllLight (google.protobuf.Empty) returns (Lights);
	rpc UpdateLight (LightDTO) returns (google.protobuf.Empty);
	rpc DeleteLight (DeleteRequestDTO) returns (google.protobuf.Empty);
}

message LightDTO{
	string id = 1;
	double value = 2;
	double reference = 3;
	LightUnit unit = 4;
	RoomDTO room = 5;
}

message Lights{ 
	   repeated LightDTO items = 1;
}

message NullableLightDTO{
	oneof kind{
		LightDTO light = 1;
		google.protobuf.Empty null = 2; 
	}
}

message CreateLightRequest{ 
	string id = 1;	
	double value = 2;
	double reference = 3;
	LightUnit unit = 4;
	RoomDTO room = 5;
}
service Room {
	rpc CreateRoom (CreateRoomRequest) returns (RoomDTO);
	rpc GetAllRoom (google.protobuf.Empty) returns (Rooms);
	rpc UpdateRoom(RoomDTO) returns (google.protobuf.Empty);
	rpc AddRoom(RoomDTO) returns (google.protobuf.Empty);
	rpc RemoveRoom(RoomDTO) returns (google.protobuf.Empty);
	rpc AddAgreementToRoom (AgreementRoomRelationDTO) returns (google.protobuf.Empty);
	rpc RemoveAgreementFromRoom (AgreementRoomRelationDTO) returns (google.protobuf.Empty);
	rpc DeleteRoom(DeleteRequestDTO) returns (google.protobuf.Empty);
}

message RoomDTO{
	int32 number = 1;
	bool isRentable = 2;
	bool isOcupated = 3;
	Price rentalPrice =4;
	bool isClimatization = 5;
	bool isIlumination = 6;
	RoomType roomType = 7;
	SmokeDTO smoke = 8;
	TemperatureDTO temperature = 9;
	LightDTO light = 10 ;
	string id = 11;

}
message Rooms {
	repeated RoomDTO item = 1;
}
message NullableRoomDTO {
	oneof kind{
		RoomDTO room = 1;
		google.protobuf.NullValue null = 2;
	}
}
message CreateRoomRequest{
	int32 number = 1;
	bool isRentable = 2;
	bool isOcupated = 3;
	Price rentalPrice =4;
	bool isClimatization = 5;
	bool isIlumination = 6;
	RoomType roomType = 7;
	SmokeDTO smoke = 8;
	TemperatureDTO temperature = 9;
	LightDTO light = 10 ;
	string id = 11;
}
message AgreementRoomRelationDTO{
	string RoomId = 1;
	string AgreementId = 2;	
}

service Smoke{
	rpc CreateSmoke (CreateSmokeRequest) returns (SmokeDTO);
	rpc GetSmoke (GetRequestDTO) returns (NullableSmokeDTO);
	rpc GetAllSmoke (google.protobuf.Empty) returns (Smokes);
	rpc UpdateSmoke (SmokeDTO) returns (google.protobuf.Empty);
	rpc DeleteSmoke (DeleteRequestDTO) returns (google.protobuf.Empty);
}

message SmokeDTO{
	string id = 1;
	double value = 2;
	double reference = 3;
	SmokeUnit unit = 4;
	RoomDTO room = 5;
	bool danger = 6;
}

message Smokes{ 
	   repeated SmokeDTO items = 1;
}

message NullableSmokeDTO{
	oneof kind{
		SmokeDTO Smoke = 1;
	    google.protobuf.Empty null = 2; 
	}
}

message CreateSmokeRequest{ 
	string id = 1;	
	double value = 2;
	double reference = 3;
	SmokeUnit unit = 4;
	RoomDTO room = 5;
	bool danger = 6;
}
service Temperature{
	rpc CreateTemperature (CreateTemperatureRequest) returns (TemperatureDTO);
	rpc GetTemperature (GetRequestDTO) returns (NullableTemperatureDTO);
	rpc GetAllTemperature (google.protobuf.Empty) returns (Temperatures);
	rpc UpdateTemperature (TemperatureDTO) returns (google.protobuf.Empty);
	rpc DeleteTemperature (DeleteRequestDTO) returns (google.protobuf.Empty);
}

message TemperatureDTO{
	string id = 1;
	double value = 2;
	double reference = 3;
	TempUnit unit = 4;
	RoomDTO room = 5;
}

message Temperatures{ 
	   repeated TemperatureDTO items = 1;
}

message NullableTemperatureDTO{
	oneof kind{
		TemperatureDTO Temperature = 1;
				google.protobuf.Empty null = 2; 
	}
}

message CreateTemperatureRequest{ 
	string id = 1;	
	double value = 2;
	double reference = 3;
	TempUnit unit = 4;
	RoomDTO room = 5;
}
