syntax = "proto3";

option csharp_namespace = "SmartHotel.GrpcProtos";

package GrpcProtos;

import "google/protobuf/empty.proto";
import "common.proto";

service Variable{
	rpc CreateVariable (CreateVariableRequest) returns (VariableDTO);
	rpc GetVariable (GetRequest) returns (NullableVariableDTO);
	rpc GetAllVariable (google.protobuf.Empty) returns (Variables);
	rpc UpdateVariable (VariableDTO) returns (google.protobuf.Empty);
	rpc DeleteVariable (DeleteRequestDTO) returns (google.protobuf.Empty);
}

message VariableDTO{
	string id = 1;
	double value = 2;
	double reference = 3;
}

message Variables{ 
	   repeated VariableDTO
items = 1;
}

message NullableVariableDTO{
	oneof kind{
		LightDTO Variable = 1;
	}
}

message CreateVariableRequest{ 
	double value = 1;
	double reference = 2;
}