<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	  <NuGetAudit>false</NuGetAudit>
  </PropertyGroup>

	<ItemGroup>
		<Protobuf Include="*.proto" GrpcServices="Both" />
	</ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentResults" Version="3.16.0" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
    <PackageReference Include="MediatR" Version="12.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartHotel.Contracts\SmartHotel.Contracts.csproj" />
    <ProjectReference Include="..\SmartHotel.GrpcProtos\SmartHotel.GrpcProtos.csproj" />
    <ProjectReference Include="..\SmartHotel.Persistence\SmartHotel.Persistence.csproj" />
  </ItemGroup>

</Project>
