// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartHotel.Persistence.Contexts;

#nullable disable

namespace SmartHotel.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250524000853_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartHotel.Domain.Entities.Agreement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Clientemail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FinalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Agreements", (string)null);
                });

            modelBuilder.Entity("SmartHotel.Domain.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsClimatizationOn")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsIluminationOn")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOcupated")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRentable")
                        .HasColumnType("boolean");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("SmartHotel.Domain.Entities.Variable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Reference")
                        .HasColumnType("double precision");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Variables");
                });

            modelBuilder.Entity("SmartHotel.Domain.Entities.Light", b =>
                {
                    b.HasBaseType("SmartHotel.Domain.Entities.Variable");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<bool>("TurnOn")
                        .HasColumnType("boolean");

                    b.Property<int>("Unit")
                        .HasColumnType("integer");

                    b.HasIndex("RoomId")
                        .IsUnique();

                    b.ToTable("Lights", (string)null);
                });

            modelBuilder.Entity("SmartHotel.Domain.Entities.Smoke", b =>
                {
                    b.HasBaseType("SmartHotel.Domain.Entities.Variable");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<int>("Unit")
                        .HasColumnType("integer");

                    b.HasIndex("RoomId")
                        .IsUnique();

                    b.ToTable("Smokes", (string)null);
                });

            modelBuilder.Entity("SmartHotel.Domain.Entities.Temperature", b =>
                {
                    b.HasBaseType("SmartHotel.Domain.Entities.Variable");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<bool>("TurnOn")
                        .HasColumnType("boolean");

                    b.Property<int>("Unit")
                        .HasColumnType("integer");

                    b.HasIndex("RoomId")
                        .IsUnique();

                    b.ToTable("Temperatures", (string)null);
                });

            modelBuilder.Entity("SmartHotel.Domain.Entities.Agreement", b =>
                {
                    b.HasOne("SmartHotel.Domain.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartHotel.Domain.Entities.Room", null)
                        .WithMany("Agreements")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SmartHotel.Domain.ValueObjects.Price", "Price", b1 =>
                        {
                            b1.Property<Guid>("AgreementId")
                                .HasColumnType("uuid");

                            b1.Property<int>("MoneyType")
                                .HasColumnType("integer");

                            b1.Property<double>("Value")
                                .HasColumnType("double precision");

                            b1.HasKey("AgreementId");

                            b1.ToTable("Agreements");

                            b1.WithOwner()
                                .HasForeignKey("AgreementId");
                        });

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SmartHotel.Domain.Entities.Room", b =>
                {
                    b.OwnsOne("SmartHotel.Domain.ValueObjects.Price", "RentalPrice", b1 =>
                        {
                            b1.Property<Guid>("RoomId")
                                .HasColumnType("uuid");

                            b1.Property<int>("MoneyType")
                                .HasColumnType("integer");

                            b1.Property<double>("Value")
                                .HasColumnType("double precision");

                            b1.HasKey("RoomId");

                            b1.ToTable("Rooms");

                            b1.WithOwner()
                                .HasForeignKey("RoomId");
                        });

                    b.OwnsOne("SmartHotel.Domain.ValueObjects.RoomType", "RoomType", b1 =>
                        {
                            b1.Property<Guid>("RoomId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Capacity")
                                .HasColumnType("integer");

                            b1.Property<int>("Category")
                                .HasColumnType("integer");

                            b1.HasKey("RoomId");

                            b1.ToTable("Rooms");

                            b1.WithOwner()
                                .HasForeignKey("RoomId");
                        });

                    b.Navigation("RentalPrice")
                        .IsRequired();

                    b.Navigation("RoomType")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartHotel.Domain.Entities.Light", b =>
                {
                    b.HasOne("SmartHotel.Domain.Entities.Variable", null)
                        .WithOne()
                        .HasForeignKey("SmartHotel.Domain.Entities.Light", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartHotel.Domain.Entities.Room", "Room")
                        .WithOne("Light")
                        .HasForeignKey("SmartHotel.Domain.Entities.Light", "RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SmartHotel.Domain.Entities.Smoke", b =>
                {
                    b.HasOne("SmartHotel.Domain.Entities.Variable", null)
                        .WithOne()
                        .HasForeignKey("SmartHotel.Domain.Entities.Smoke", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartHotel.Domain.Entities.Room", "Room")
                        .WithOne("Smoke")
                        .HasForeignKey("SmartHotel.Domain.Entities.Smoke", "RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SmartHotel.Domain.Entities.Temperature", b =>
                {
                    b.HasOne("SmartHotel.Domain.Entities.Variable", null)
                        .WithOne()
                        .HasForeignKey("SmartHotel.Domain.Entities.Temperature", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartHotel.Domain.Entities.Room", "Room")
                        .WithOne("Temperature")
                        .HasForeignKey("SmartHotel.Domain.Entities.Temperature", "RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SmartHotel.Domain.Entities.Room", b =>
                {
                    b.Navigation("Agreements");

                    b.Navigation("Light")
                        .IsRequired();

                    b.Navigation("Smoke")
                        .IsRequired();

                    b.Navigation("Temperature")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
